version: '3.8'

services:
  db:
    container_name: note_db
    image: postgres:13.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=DeadlineDay
    ports:
      - "5432"
volumes:
  postgres_data: