version: '3.8'

services:
  app:
    container_name: node-app
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    container_name: postgres-db
    image: postgres:14
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: DeadlineDay
    ports:
      - "5432:5432"

volumes:
  postgres-data: